// Code generated by go generate
// This file was generated by robots at 2019-04-22 15:35:59.830774549 +0000 UTC

package nagopher

import (
	"encoding/json"
	"errors"
)

// OptionalPerfData is an optional PerfData.
type OptionalPerfData struct {
	value *PerfData
}

// NewOptionalPerfData creates an optional.OptionalPerfData from a PerfData.
func NewOptionalPerfData(v PerfData) OptionalPerfData {
	return OptionalPerfData{&v}
}

// Set sets the PerfData value.
func (o *OptionalPerfData) Set(v PerfData) {
	o.value = &v
}

// Get returns the PerfData value or an error if not present.
func (o OptionalPerfData) Get() (PerfData, error) {
	if !o.Present() {
		var zero PerfData
		return zero, errors.New("value not present")
	}
	return *o.value, nil
}

// Present returns whether or not the value is present.
func (o OptionalPerfData) Present() bool {
	return o.value != nil
}

// OrElse returns the PerfData value or a default value if the value is not present.
func (o OptionalPerfData) OrElse(v PerfData) PerfData {
	if o.Present() {
		return *o.value
	}
	return v
}

// If calls the function f with the value if the value is present.
func (o OptionalPerfData) If(fn func(PerfData)) {
	if o.Present() {
		fn(*o.value)
	}
}

func (o OptionalPerfData) MarshalJSON() ([]byte, error) {
	if o.Present() {
		return json.Marshal(o.value)
	}
	return json.Marshal(nil)
}

func (o *OptionalPerfData) UnmarshalJSON(data []byte) error {

	if string(data) == "null" {
		o.value = nil
		return nil
	}

	var value PerfData

	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	o.value = &value
	return nil
}
